<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <!-- Permite ejecutar el build framework-dependent con un runtime más nuevo (.NET 9, 10...) -->
    <RollForward>Major</RollForward>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationIcon>megadeck.ico</ApplicationIcon>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.3.22" />
    <PackageReference Include="Avalonia.Desktop" Version="11.3.22" />
    <PackageReference Include="Classic.Avalonia.Theme" Version="11.3.0.3" />
  </ItemGroup>

  <ItemGroup>
    <AvaloniaResource Include="megadeck.ico" />
    <AvaloniaResource Include="Assets/**" />
  </ItemGroup>

  <!-- 🔽 Copia automática de RetroArch (Windows y Linux) y roms -->
  <ItemGroup>
    <None Include="engine/**/*" CopyToOutputDirectory="PreserveNewest" />
    <None Include="engine-linux/**/*" CopyToOutputDirectory="PreserveNewest" />
    <None Include="roms/**/*" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
